### ISSUE TITLE
MaxKB connect BRConnector as OpenAI successfully, but get error when perform inference

### ISSUE THREAD

**Issue by ensean** [aws-samples/sample-connector-for-bedrock#1]
* MaxKB supports add OpenAI endpoint with API host alias
<img width="599" alt="image" src="https://github.com/aws-samples/sample-connector-for-bedrock/assets/12255172/4c0ad79f-3175-40e0-acf4-c089a12c0d5a">

* The BR connector is connected successfully

* But gots error when perform inference with the UI MaxKB provided
<img width="849" alt="image" src="https://github.com/aws-samples/sample-connector-for-bedrock/assets/12255172/5ccf7f99-e194-4a32-9ed4-c0db154197b4">

* CW logs shows that the prompt is accepted by bedrock and the response is returned by bedrock
```
{
    "schemaType": "ModelInvocationLog",
    "schemaVersion": "1.0",
    "timestamp": "2024-05-22T07:29:50Z",
    "accountId": "123456789012",
    "identity": {
        "arn": "arn:aws:iam::123456789012:user/br"
    },
    "region": "us-west-2",
    "requestId": "fc9e60a6-680f-4a80-8b21-da1436214f0c",
    "operation": "InvokeModelWithResponseStream",
    "modelId": "anthropic.claude-3-sonnet-20240229-v1:0",
    "input": {
        "inputContentType": "application/json",
        "inputBodyJson": {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 4096,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "MaxKB 支持哪些大语言模型？"
                        }
                    ]
                }
            ],
            "temperature": 0.7,
            "top_p": 1,
            "top_k": 50
        },
        "inputTokenCount": 22
    },
    "output": {
        "outputContentType": "application/json",
        "outputBodyJson": [
            {
                "type": "message_start",
                "message": {
                    "id": "msg_01JxtT7pWxfxLnEP1vT83egY",
                    "type": "message",
                    "role": "assistant",
                    "content": [],
                    "model": "claude-3-sonnet-28k-20240229",
                    "stop_reason": null,
                    "stop_sequence": null,
                    "usage": {
                        "input_tokens": 22,
                        "output_tokens": 1
                    }
                }
            },
            {
                "type": "content_block_start",
                "index": 0,
                "content_block": {
                    "type": "text",
                    "text": ""
                }
            },
            {
                "type": "content_block_delta",
                "index": 0,
                "delta": {
                    "type": "text_delta",
                    "text": "Max"
                }
            },
            {
                "type": "content_block_delta",
                "index": 0,
                "delta": {
                    "type": "text_delta",
                    "text": "K"
                }
            },
            {
                "type": "content_block_delta",
                "index": 0,
                "delta": {
                    "type": "text_delta",
                    "text": "B"
                }
            },
            {
                "type": "content_block_delta",
                "index": 0,
                "delta": {
                    "type": "text_delta",
                    "text": "目"
                }
            },
            ...
```

**Comment by cloudbeer** [comment]
MaxKB error logs:

```
2024-05-27 11:01:31 [base_chat_step ERROR] object of type 'NoneType' has no len():Traceback (most recent call last):
  File "/opt/maxkb/app/apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py", line 55, in event_content
    for chunk in response:
  File "/opt/py3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 249, in stream
    raise e
  File "/opt/py3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 229, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/opt/py3/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 422, in _stream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

While BRConnector uses the sse (Server-Sent Events) method for output, it's not entirely in the OpenAI model. This part needs to be evaluated.

**Comment by cloudbeer** [comment]
Now, MaxKB is supported. Please refer to the following steps:

- Use the docker image version 0.0.5 or later.
- In the management backend /manager, add a model with the same name as the one you set in your MaxKB, e.g., gpt-3.5-turbo.
- Ensure that your API Key can access to this model. You can set it in the API Key or in the Group settings.

现在 已经可以支持 MaxKB 了，请参考如下的步骤：
- 使用 docker image 0.0.5+ 版本
- 在管理后台 /manager 添加一个模型，模型的名称请和您 MaxKB 中设置的名称一致：比如 gpt-3.5-turbo
- 请保证您的 API Key 具有访问该模型的权限，在 API Key 或者 在 Group 中设置。
