### ISSUE TITLE
err Error: connect EMFILE

### ISSUE THREAD

**Issue by zhuermu** [aws-samples/sample-connector-for-bedrock#56]
when I use the connector to two days after, the web server  error: "
err Error: connect EMFILE [127.0.0.15432](http://127.0.0.1:5432/) - Local (undefined:undefined)
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PGClient.query (/app/server/util/postgres.js:39:24)
    at async PGClient.list (/app/server/util/postgres.js:136:26)
    at async Object.loadData (/app/server/util/cache.js:30:26) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'connect',
  address: '[127.0.0.1](http://127.0.0.1/)',
  port: 5432"

I think maybe this problem is the db connect not use pool or maybe it's not properly closing the connection?

**Comment by BlastShadowsong** [comment]
I also encountered this problem, which can cause the docker container to become "unhealthy" after running for about a day, leading to the service becoming unavailable.

**Comment by yancl** [comment]
I think the problem is [log file descriptor leak](https://github.com/aws-samples/sample-connector-for-bedrock/blob/main/src/middleware/handlers.ts#L149), it will create two new fd every time `loggerHandler` called and never released. 

* number of log file descriptors in the nodejs process.(314452):
```
lsof -p 314452 | grep 'combined.log' | wc -l
961
```
* after temp fix:
```
lsof -p 340793 | grep 'combined.log' | wc -l
1
```

@wengkaer will you please have a look?

**Comment by cloudbeer** [comment]
When using winston, I incorrectly called the createLogger method in the middleware, causing a file handle leak.

This error will be fixed in 0.0.19.

**Comment by cloudbeer** [comment]
> I think the problem is [log file descriptor leak](https://github.com/aws-samples/sample-connector-for-bedrock/blob/main/src/middleware/handlers.ts#L149), it will create two new fd every time `loggerHandler` called and never released.
> 
> * number of log file descriptors in the nodejs process.(314452):
> 
> ```
> lsof -p 314452 | grep 'combined.log' | wc -l
> 961
> ```
> 
> * after temp fix:
> 
> ```
> lsof -p 340793 | grep 'combined.log' | wc -l
> 1
> ```
> 
> @wengkaer will you please have a look?

Thank you for pointing out the error you described. This error will be fixed in the next version 0.0.19.
